package Client_Java.WordyApp;

/**
* WordyApp/WordyGameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Monday, May 8, 2023 9:51:43 PM CST
*/

public final class WordyGameHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyGame value = null;

  public WordyGameHolder ()
  {
  }

  public WordyGameHolder (WordyGame initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyGameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyGameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyGameHelper.type ();
  }

}
