package Client_Java.WordyApp;


/**
* WordyApp/WordyGameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Monday, May 8, 2023 9:51:43 PM CST
*/

public interface WordyGameOperations 
{
  String login (String username, String password, String result);
  void logout (String username);
  boolean register (String username, String password);
  int getUserIDFromUsername (String username);
  String[] getPlayerList ();
  String[] getFiveLongestWords ();
  String[] getTopFivePlayers ();
  String[] getWordsData ();
  String getRandomLetters (int roundNumber);
  boolean validateInput (String randomLetters, String inputString, String[] data);
  void updateLongestWordFormed (int userID, String wordFormed, String roomName);
  void insertIntoLeaderboardTable (int userID, String longestWord, int matchesWon);
  void setLongestWordToNull (String roomName);
  int getLongestWordLength (int userID);
  void compareWordFormedToLongestWord (int userID, String wordFormed);
  boolean checkPointsAchieved (String roomName);
  boolean checkExistingUserID (int userID);
  void updateMatchesWon (int userID);
  int modifyPointsAchieved (int userID, String roomName);
  void startNewWaitingRoom ();
  boolean joinWaitingRoom (String username);
  void leaveWaitingRoom (String username);
  String[] checkWaitingRoomStatus ();
  int displayScores (int userID);
  String[] getPlayersInGameSession (String roomName);
} // interface WordyGameOperations
