package Server_Java.WordyApp;


/**
* WordyApp/arrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Monday, May 8, 2023 9:51:22 PM CST
*/

public final class arrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public arrayHolder ()
  {
  }

  public arrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = arrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    arrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return arrayHelper.type ();
  }

}
