package Server_Java.WordyApp;


/**
* WordyApp/WordyGamePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Monday, May 8, 2023 9:51:22 PM CST
*/

public abstract class WordyGamePOA extends org.omg.PortableServer.Servant
 implements WordyGameOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new Integer (0));
    _methods.put ("logout", new Integer (1));
    _methods.put ("register", new Integer (2));
    _methods.put ("getUserIDFromUsername", new Integer (3));
    _methods.put ("getPlayerList", new Integer (4));
    _methods.put ("getFiveLongestWords", new Integer (5));
    _methods.put ("getTopFivePlayers", new Integer (6));
    _methods.put ("getWordsData", new Integer (7));
    _methods.put ("getRandomLetters", new Integer (8));
    _methods.put ("validateInput", new Integer (9));
    _methods.put ("updateLongestWordFormed", new Integer (10));
    _methods.put ("insertIntoLeaderboardTable", new Integer (11));
    _methods.put ("setLongestWordToNull", new Integer (12));
    _methods.put ("getLongestWordLength", new Integer (13));
    _methods.put ("compareWordFormedToLongestWord", new Integer (14));
    _methods.put ("checkPointsAchieved", new Integer (15));
    _methods.put ("checkExistingUserID", new Integer (16));
    _methods.put ("updateMatchesWon", new Integer (17));
    _methods.put ("modifyPointsAchieved", new Integer (18));
    _methods.put ("startNewWaitingRoom", new Integer (19));
    _methods.put ("joinWaitingRoom", new Integer (20));
    _methods.put ("leaveWaitingRoom", new Integer (21));
    _methods.put ("checkWaitingRoomStatus", new Integer (22));
    _methods.put ("displayScores", new Integer (23));
    _methods.put ("getPlayersInGameSession", new Integer (24));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordyApp/WordyGame/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String result = in.read_string ();
         String $result = null;
         $result = this.login (username, password, result);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // WordyApp/WordyGame/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // WordyApp/WordyGame/register
       {
         String username = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.register (username, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // WordyApp/WordyGame/getUserIDFromUsername
       {
         String username = in.read_string ();
         int $result = (int)0;
         $result = this.getUserIDFromUsername (username);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // WordyApp/WordyGame/getPlayerList
       {
         String $result[] = null;
         $result = this.getPlayerList ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 5:  // WordyApp/WordyGame/getFiveLongestWords
       {
         String $result[] = null;
         $result = this.getFiveLongestWords ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 6:  // WordyApp/WordyGame/getTopFivePlayers
       {
         String $result[] = null;
         $result = this.getTopFivePlayers ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 7:  // WordyApp/WordyGame/getWordsData
       {
         String $result[] = null;
         $result = this.getWordsData ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 8:  // WordyApp/WordyGame/getRandomLetters
       {
         int roundNumber = in.read_long ();
         String $result = null;
         $result = this.getRandomLetters (roundNumber);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // WordyApp/WordyGame/validateInput
       {
         String randomLetters = in.read_string ();
         String inputString = in.read_string ();
         String data[] = arrayHelper.read (in);
         boolean $result = false;
         $result = this.validateInput (randomLetters, inputString, data);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 10:  // WordyApp/WordyGame/updateLongestWordFormed
       {
         int userID = in.read_long ();
         String wordFormed = in.read_string ();
         String roomName = in.read_string ();
         this.updateLongestWordFormed (userID, wordFormed, roomName);
         out = $rh.createReply();
         break;
       }

       case 11:  // WordyApp/WordyGame/insertIntoLeaderboardTable
       {
         int userID = in.read_long ();
         String longestWord = in.read_string ();
         int matchesWon = in.read_long ();
         this.insertIntoLeaderboardTable (userID, longestWord, matchesWon);
         out = $rh.createReply();
         break;
       }

       case 12:  // WordyApp/WordyGame/setLongestWordToNull
       {
         String roomName = in.read_string ();
         this.setLongestWordToNull (roomName);
         out = $rh.createReply();
         break;
       }

       case 13:  // WordyApp/WordyGame/getLongestWordLength
       {
         int userID = in.read_long ();
         int $result = (int)0;
         $result = this.getLongestWordLength (userID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 14:  // WordyApp/WordyGame/compareWordFormedToLongestWord
       {
         int userID = in.read_long ();
         String wordFormed = in.read_string ();
         this.compareWordFormedToLongestWord (userID, wordFormed);
         out = $rh.createReply();
         break;
       }

       case 15:  // WordyApp/WordyGame/checkPointsAchieved
       {
         String roomName = in.read_string ();
         boolean $result = false;
         $result = this.checkPointsAchieved (roomName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 16:  // WordyApp/WordyGame/checkExistingUserID
       {
         int userID = in.read_long ();
         boolean $result = false;
         $result = this.checkExistingUserID (userID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 17:  // WordyApp/WordyGame/updateMatchesWon
       {
         int userID = in.read_long ();
         this.updateMatchesWon (userID);
         out = $rh.createReply();
         break;
       }

       case 18:  // WordyApp/WordyGame/modifyPointsAchieved
       {
         int userID = in.read_long ();
         String roomName = in.read_string ();
         int $result = (int)0;
         $result = this.modifyPointsAchieved (userID, roomName);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 19:  // WordyApp/WordyGame/startNewWaitingRoom
       {
         this.startNewWaitingRoom ();
         out = $rh.createReply();
         break;
       }

       case 20:  // WordyApp/WordyGame/joinWaitingRoom
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.joinWaitingRoom (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 21:  // WordyApp/WordyGame/leaveWaitingRoom
       {
         String username = in.read_string ();
         this.leaveWaitingRoom (username);
         out = $rh.createReply();
         break;
       }

       case 22:  // WordyApp/WordyGame/checkWaitingRoomStatus
       {
         String $result[] = null;
         $result = this.checkWaitingRoomStatus ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 23:  // WordyApp/WordyGame/displayScores
       {
         int userID = in.read_long ();
         int $result = (int)0;
         $result = this.displayScores (userID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 24:  // WordyApp/WordyGame/getPlayersInGameSession
       {
         String roomName = in.read_string ();
         String $result[] = null;
         $result = this.getPlayersInGameSession (roomName);
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordyApp/WordyGame:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public WordyGame _this()
  {
    return WordyGameHelper.narrow(
    super._this_object());
  }

  public WordyGame _this(org.omg.CORBA.ORB orb)
  {
    return WordyGameHelper.narrow(
    super._this_object(orb));
  }


} // class WordyGamePOA
