package Server_Java.WordyApp;


/**
* WordyApp/WordyGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Monday, May 8, 2023 9:51:22 PM CST
*/

public interface WordyGame extends WordyGameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface WordyGame
